name: chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.12.1
  firebase_database: ^12.4.6
  firebase_messaging: ^16.4.3
  flutter_local_notifications: ^22.2.0
  http: ^1.6.0
  shared_preferences: ^2.2.2
  qr_flutter: ^4.0.0
  webview_flutter: ^4.14.0
  url_launcher: ^6.1.12
  video_player: ^2.6.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
