// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC87CtoCUXb4mbTle76E-JRcRGxydx5FJ8',
    appId: '1:896451120275:web:30ba865169a5ac293c1166',
    messagingSenderId: '896451120275',
    projectId: 'dontcheckme',
    authDomain: 'dontcheckme.firebaseapp.com',
    storageBucket: 'dontcheckme.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRwL04avAWC0NPXmLeYQsIAYOEyBq50dI',
    appId: '1:896451120275:android:3c229feaaf8dbe803c1166',
    messagingSenderId: '896451120275',
    projectId: 'dontcheckme',
    storageBucket: 'dontcheckme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoQWhu5On8xhgdd_KNFqW_XSTYp4z5-YM',
    appId: '1:896451120275:ios:e7b2068bcd4cd65e3c1166',
    messagingSenderId: '896451120275',
    projectId: 'dontcheckme',
    storageBucket: 'dontcheckme.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoQWhu5On8xhgdd_KNFqW_XSTYp4z5-YM',
    appId: '1:896451120275:ios:e7b2068bcd4cd65e3c1166',
    messagingSenderId: '896451120275',
    projectId: 'dontcheckme',
    storageBucket: 'dontcheckme.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC87CtoCUXb4mbTle76E-JRcRGxydx5FJ8',
    appId: '1:896451120275:web:f81c8dcac8c442e03c1166',
    messagingSenderId: '896451120275',
    projectId: 'dontcheckme',
    authDomain: 'dontcheckme.firebaseapp.com',
    storageBucket: 'dontcheckme.firebasestorage.app',
  );
}
